#!/bin/bash
# HardwareTest - Scripts to stress test the hardware of your computer.
# Copyright (C) [Year] Michael McMahon
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# WARNING: USE AT YOUR OWN RISK. THESE SCRIPTS INTENTIONALLY PLACE STRAIN ON
# YOUR SYSTEM. IF YOU CANNOT ACCEPT HARDWARE FAILURE, DO NOT USE THESE SCRIPTS.
# USE THESE SCRIPTS ON NEW SYSTEMS ONLY. I AM NOT RESPONSIBLE FOR BROKEN
# HARDWARE OR LOSS OF DATA. READ AND UNDERSTAND THE SCRIPT BEFORE RUNNING ON
# ANY HARDWARE.
